site_name: ILO

nav:
  - Bonnvenon: index.md
  - Asocio:
    - Statuso: Asocio/statuts_ILO.md
    - La "revmedikamenta trinkaĵo": Asocio/potion.md
    - Ĝeneralaj asembleoj:
      - AG_2018: Asocio/AG_2018.md
      - AG_2019: Asocio/AG_2019.md
    - Koncertoj:
      - Dampière: Asocio/dampiere.md
      - Le Chesnay: Asocio/le_chesnay.md
  - Kursoj:
    - Historio: Kursoj/historio.md
    - Gramatiko: Kursoj/gramatiko.md
  - Tradukoj: Tradukoj/tradukoj.md 

theme:
  name: 'material'
  language: 'fr'
  palette:
    primary: 'green'
    
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
